name: Generate Arduino Code from Model

on:
  repository_dispatch:
    types: [generate-arduino-code]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers

      - name: Generate Arduino Code
        run: |
          mkdir -p output
          echo "${{ github.event.client_payload.prompt }}" > prompt.txt
          python backend/generate.py prompt.txt output/

      - name: Commit and Push Output
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output/*
          git commit -m "Generate Arduino code from model"
          git push
