name: Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set up GH_TOKEN
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo "Token is set successfully"

    - name: Run server and client
      run: |
        npm start  # Menjalankan server.js dan index.mjs secara bersamaan
